[package]
name = "platform-version"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Bincode based serialization and deserialization"
version = "1.0.0-dev.7"
edition = "2021"
rust-version = "1.76"
license = "MIT"

[dependencies]
thiserror = { version = "1.0" }
ferment-interfaces = { path = "../../../ferment/ferment-interfaces" }
ferment-macro = { path = "../../../ferment/ferment-macro" }

[build-dependencies]
ferment = { path = "../../../ferment/ferment" }

[features]
mock-versions = []
